### ISSUE TITLE
checking fails for files without extension

### ISSUE THREAD

**Issue by atomGit** [okdana/mp3crc#1]
this is unusual it seems as all other tools i use to work with mp3s do not require that a file have an extension

**Comment by okdana** [comment]
You mean like when you give a file directly on the command line? I think that's because i mainly intended it to be used with entire directories, and it'd be slow to check for the MP3-ness of every single file it encountered using anything besides the extension. But it does seem like it shouldn't apply that check to files you give it explicitly, yeah.

I haven't touched this project in a while, so i'm a little rusty on it, but i'll see if i can fix this soon

**Comment by atomGit** [comment]
well hello there :) wasn't sure you'd respond given the 4 year vacation LOL

> You mean like when you give a file directly on the command line?

yes - i'm using mp3sum in a shell script and i sanitize file names by temporarily renaming the files 'working', no extension

i've already worked around the problem if you'd rather not mess with the code though

as long as i have you on the line, i have a Q about CRC ... i can pass an mp3 through mp3info and mp3 diags and neither detect CRC info, yet mp3sum does - why is that?

i'm guessing that other programs are looking for CRC in the audio frames whereas you seem to be looking at headers - so is there different ways that CRC info can be written for the purpose of verifying the actual audio stream (ignoring other metadata)?

even ffprobe (-err_detect crccheck) produces nothing, yet mp3sum will

**Comment by okdana** [comment]
> i've already worked around the problem if you'd rather not mess with the code though

I've been meaning to, because i didn't really know what i was doing when i wrote this, and that kind of bothers me. Just haven't got around to it

> as long as i have you on the line, i have a Q about CRC ... i can pass an mp3 through mp3info and mp3 diags and neither detect CRC info, yet mp3sum does - why is that?
>
> i'm guessing that other programs are looking for CRC in the audio frames whereas you seem to be looking at headers - so is there different ways that CRC info can be written for the purpose of verifying the actual audio stream (ignoring other metadata)?

The 'info tag' this tool uses is specific to the LAME encoder, and a lot of MP3 utilities just ignore it. (Or they did in 2011 when i was first working on this. I assume that's still true, because even at the time it seemed like there wasn't a lot of activity in the MP3-tool space. e.g., `mp3info` hasn't been updated since 2006)

The MPEG format itself allows for an optional CRC at the beginning of each audio frame which could be used (probably more accurately) instead of the info tag for this purpose, but i'm pretty sure the reason i didn't do that is that almost nobody actually enables frame CRCs. I'm not super familiar with FFmpeg, but if the `crccheck` thing is trying to use those CRC frames that's probably why it doesn't do much for you

**Comment by atomGit** [comment]
thanks for confirming what i thought to be the case

LAME can write CRC checksums to the audio frames ( -p is the option ) and it's disabled by default apparently, which explains why some software isn't reporting a CRC

i think the way you're checking is the best way far as i'm concerned - if one enabled -p for LAME, that CRC data apparently *displaces* space that would otherwise be used for the audio - for CBR, that means a reduction in quality - it seems VBR can be affected also, though i'm not entirely sure in what way

i always used to encode @ 320 CBR and now i know that's the wrong way to go - the better way is VBR at whatever quality you need (-qscale:a 0 for ffmpeg is highest quality VBR)

and thanks a ton for the info you provided - that really helps me out

**Comment by okdana** [comment]
I think this should be fixed. It'll be a little slower now because the extension check is done serially before the verification. Ideally i would have fixed that properly, but i just don't have much any energy for it at the moment. It's probably only a minor issue when checking thousands of files recursively, anyway

**Comment by atomGit** [comment]
thanks okdana
